service: aws-ec2-securityGroups

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - ec2:DescribeSecurityGroups
    Resource: "*"
plugins:
  - serverless-offline

functions:
  list:
    handler: handler/securityGroupsList.index
    events:
      - http:
          path: /
          method: get
          authorizer: authorizerFunc # execute this before the list endpoint
  authorizerFunc:
    handler: handler/authorizer.index
